# Config file for automatic testing at travis-ci.org
sudo: false
dist: "bionic"
language: python

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

python:
  - "3.8"
  - "pypy"

# command to install dependencies
install: 
  - pip3 install -r requirements.txt

# command to run tests
script:
  - py.test
